dataset:
  name: Liquid3d

  dataset_path: /workdir/_datasets/CCONV/dpi_dam_break # path to dataset
  #cache_dir: ./logs/cache/

model:
  name: GNS
  ckpt_path: # path to checkpoint
  window_dens: poly6
  particle_radii: [0.02]
  connectivity_radius: 0.052
  timestep: 0.0166666666 # depends on stride of dataloader (timestep * stride)
  grav: -8.91818181818182
  message_passing_steps: 10

  #transformation:
  #  grav_eqvar: [0, -1, 0]


  loss:
    weighted_mse:
      typ: weighted_mse
      fac: 128.0
      gamma: 0.5
      scale: 1.1
      fluid_method: linear
      #pre_scale: 0.04

pipeline:
  name: Simulator
  version: 3d

  max_epoch: 50
  batch_size: 1
  iter: 1000

  window_bnds: []
  windows: [2]
  time_blend: 200

  warm_up_bnds: []
  max_warm_up: [0]

  optimizer:
    lr_boundaries: [
      25000,
      30000,
      35000,
      40000,
      45000
    ]
    lr_values: [
      0.001,
      0.0005,
      0.00025,
      0.000125,
      0.0000625,
      0.00003125,
    ]
    loss_boundaries: [
      25000,
      30000,
      35000,
      40000,
      45000
    ]
    loss_values: [
      5,
      2.5,
      1.25,
      0.625,
      0.3125,
      0.15625
    ]

  base_data_dir : ../data/output
  main_log_dir: ./logs
  train_sum_dir: ./train_log
  output_dir: ./output
  save_ckpt_freq: 1


  data_generator:
    #translate: [-0.5, -0.5, -0.5]
    scale: [1.0, 1.0, 1.0]

    train:
      stride: 1 # update timestep accordingly!
      repeat: True
      shuffle_buffer: 512
      is2d: False
      num_workers: 1
#      sample_cnt: 25
      
      augment:
        jitter_inp:
          channels:
            pos: [0.001, 0.001, 0.001] # 1% of dx
        rotate:
          rot_axis: 1

    valid:
      stride: 1
      time_end: 10
      random_start: 200

    test:
      stride: 1
      time_start: 0
      time_end: 50


      
    

