dataset:
  name: CConvData3D

  dataset_path: /workdir/datasets/CConvData3D # path to dataset
  #cache_dir: ./logs/cache/

model:
  name: PolarNetG

  ckpt_path: # path to checkpoint
  particle_radii: [0.025]
  timestep: 0.02 # depends on stride of dataloader (timestep * stride)
  grav: -9.81
  out_scale: [0.0078125, 0.0078125, 0.0078125] 
  rest_dens: 1000.0
  channels: 16

  #transformation:
  #  grav_eqvar: [0, -1, 0]

  loss:
    weighted_mse:
      typ: weighted_mse
      fac: 128.0
      gamma: 0.5
      neighbor_scale: 0.01
      box_neighbor_scale: 0.05
      scale: 1.0
      #pre_scale: 0.04
    weighted_mse_vel:
      typ: weighted_mse_vel
      fac: 128.0
      gamma: 0.5
      neighbor_scale: 0.01
      box_neighbor_scale: 0.05
      scale: 0.02
    dense_pbf:
      typ: dense_pbf
      fac: 128.0

  dens_feats: False
  pres_feats: False

pipeline:
  name: Simulator
  version: 3d

  max_epoch: 50
  batch_size: 4
  iter: 1000
  
  window_bnds: [15000]
  windows: [2, 3] 
  time_blend: 200

  #max_err: 0.0025 # 1/2 voxel
  max_dens_err: 0.1 # 20% density error

  warm_up_bnds: []
  max_warm_up: [0] 

  its_bnds: []
  iterations: [0] 

  optimizer:
    lr_boundaries: [
      20000,
      25000,
      30000,
      35000,
      40000,
      45000
    ]
    lr_values: [
      0.001,
      0.0005,
      0.00025,
      0.000125,
      0.0000625,
      0.00003125,
      0.000015625
    ]

  base_data_dir : ../data/output
  main_log_dir: ./logs
  train_sum_dir: ./train_log
  output_dir: ./output
  save_ckpt_freq: 1


  data_generator:
    #translate: [-0.5, -0.5, -0.5]
    scale: [1.0, 1.0, 1.0]

    train:
      stride: 1 # update timestep accordingly!
      repeat: True
      shuffle_buffer: 512
      is2d: False
      num_workers: 1
      sample_cnt: 25
      
      augment:
        jitter_inp: 
          channels: 
            pos: [0.001, 0.001, 0.001] # 1% of dx
        rotate:
          rot_axis: 1
        #rotate:
        #  strength: [1.0, 1.0, 1.0] 

      # augment:
      #   jitter: 
      #     channels: 
      #       pos: 0.001
      #       vel: 0.001
      #       grav: 0.001
      #       box: 0.001
      #       box_normals: 0.001
        
      #   shuffle: True

      #   rotate:
      #     strength: [0.0, 0.0, 1.0]

    valid:
      stride: 1
      time_end: 10
      random_start: 200

    test:
      stride: 1
      time_start: 0
      time_end: 50


      
    

